import Head from "next/head";
import Image from "next/image";

export default function Home() {
  // noinspection HtmlUnknownTarget
  return (
    <div>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex flex-col justify-center items-center bg-black">
        <main className="flex-grow">
          <div className="h-full flex justify-center items-center">
            <div className="flex-col mx-6">
              <div className="my-6">
                <h1 className="text-gray-100 text-5xl text-center">
                  This is the Home page
                </h1>
              </div>
            </div>
          </div>
        </main>

        <div className="flex-none text-gray-300 my-24">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by
            {/* <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
          </a>
        </div>
      </div>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
